version: '3.9'
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      TZ: Europe/Paris
      WEBUI_PORT: 8685
    ports:
      - 8685:8685
      - 6881:6881
      - 6881:6881/udp
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8685 || exit 1"]
  auto-remove:
    image: ghcr.io/greepthesheep/qbittorrent-auto-remove/qbittorrent-auto-remove
    container_name: qbittorrent-auto-remover
    environment:
      TZ: Europe/Paris
      EXEC_CRON: "* * * * *"
      QBIT_HOST: qbittorrent
      QBIT_PORT: 8685
      QBIT_USER: admin
      QBIT_PASS: 123456
      TASK_DELAY_DAYS: 30
      TASK_RATIO: 0.2
      TASK_DELETE_FILES: true
    restart: always
    depends_on:
      qbittorrent:
        condition: service_healthy
